version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: 3090-experiment
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
  - dependency-name: mkdocs-material
    versions:
    - 7.0.4
    - 7.0.5
    - 7.0.6
    - 7.0.7
    - 7.1.1
    - 7.1.2
  - dependency-name: pre-commit
    versions:
    - 2.11.0
    - 2.12.0
  - dependency-name: dvc
    versions:
    - 2.0.1
    - 2.0.10
    - 2.0.11
    - 2.0.12
    - 2.0.13
    - 2.0.15
    - 2.0.16
    - 2.0.17
    - 2.0.2
    - 2.0.3
    - 2.0.4
    - 2.0.5
    - 2.0.6
    - 2.0.7
  - dependency-name: radon
    versions:
    - 4.4.0
