prepare:
  split: 0.25
  seed: 42

resnet:
  name: "ResNetV2"
  repetitions_block: 2
  n_classes: 2
  img_shape: [224,224,3]

wide_resnet:
  name: "Wide ResNet"
  repetitions_block: 2
  width_factor: 2
  n_classes: 2
  img_shape: [224,224,3]

prepared_datas:
  train: "datas/prepared_datas/train.csv"
  val: "datas/prepared_datas/val.csv"
  test: "datas/prepared_datas/test.csv"

hyperparameters:
  augment: True
  batch_size: 16
  repetitions: 1
  prefetch: 1
  optimizer: "adam"
  learning_rate: 0.001
  loss_fn: "categorical_crossentropy"
  #metric_fn: "accuracy"
  metric_fn: ["accuracy"]
  epochs: 15


mlflow:
  experiment_name: wide_resnet
