prepare:
  split: 0.25
  seed: 42

resnet:
  repetitions: 5
  n_classes: 2
  img_shape: [224,224,3]

prepared_datas:
  train: "datas/prepared_datas/train.csv"
  val: "datas/prepared_datas/val.csv"
  test: "datas/prepared_datas/test.csv"

hyperparameters:
  augment: False
  batch_size: 16
  repetitions: 1
  prefetch: 1
  optimizer: "rmsprop"
  learning_rate: 0.001
  loss_fn: "categorical_crossentropy"
  metric_fn: "accuracy"
  epochs: 30

mlflow:
  experiment_name: test
