# @package _group_
raw_datas:
  n_classes: 2

raw_dataset: "datas/raw_dataset"

prepared_dataset:
  train: "datas/prepared_dataset/train.csv"
  val: "datas/prepared_dataset/val.csv"
  test: "datas/prepared_dataset/test.csv"

params:
  img_shape: [128,128,3]
  augment: True
  batch_size: 32
  repetitions: 1
  prefetch: 1
